### ISSUE TITLE
Update the About Us

### ISSUE THREAD

**Issue by maxwildersmith** [CPP-SAE-Supermileage/website#4]
Need to add information for each of the teams under the About Us component (I was thinking a general section about the club with two columns beneath, one for each team with recruitment button at the bottom, maybe put each team info in card, I am open to suggestions for this).

**Comment by The-Mills** [comment]
Include what "SAE" stands for.

**Comment by maxwildersmith** [comment]
From Arda:

> CPP SAE Supermileage was founded to engineer the most fuel
efficient vehicles to fight against the climate change. Although it’s established in Fall
2018, the team built the Cal Poly Pomona’s first ever super fuel efficient
vehicle,Moonshot, from scratch in little bit over a year with no prior experience. CPP
SAE Supermileage designs, analyzes and manufactures its own aerodynamic shell,
chassis, steering system and power control units in house with funds from sponsors
and donors, almost entirely. In an attempt to create the ultimate fuel efficiency
machine, the team decided to embrace the latest developments in machine learning,
computer vision, sensor fusion and autonomous driving, and formed into an
engineering+computer science driven organization in early 2020.

> Although we are made up from engineering and computer science students, 
welcome any student who is very motivated to go the extra mile with us!

**Comment by kjkondo** [comment]
https://github.com/CPP-SAE-Supermileage/website/pull/28
